//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Le modifiche apportate a questo file andranno perse se il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicriCancelli.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@".\DB\cancelli.db")]
        public string dbpathFile {
            get {
                return ((string)(this["dbpathFile"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c1f30d9b4f5250aa9f4cacb54abd3affd3f9f20db48844e364cdd5d2896bf552")]
        public string passwordParametriSha256 {
            get {
                return ((string)(this["passwordParametriSha256"]));
            }
        }
    }
}
